#!/bin/bash

source "$(dirname "$0")/_common.sh"
source /usr/share/yunohost/helpers

ynh_systemd_action --service_name="$app" --action="stop" --line_match="stopped" || true
yunohost service remove "$app" || true

ynh_remove_systemd_config

ynh_remove_nginx_config
ynh_app_remove_peer_nginx_config

ynh_exec_warn_less yunohost firewall disallow TCP "$public_peer_port"

ynh_secure_remove --file="$install_dir"

ynh_secure_remove --file="/var/log/$app"
